---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- dns/
- web/
- node-bramble.yaml
- node-rpi1.yaml
- node-rpi2.yaml
- https://github.com/rancher/system-upgrade-controller/releases/latest/download/crd.yaml
- https://github.com/rancher/system-upgrade-controller/releases/latest/download/system-upgrade-controller.yaml
- plan-upgrade-control-plane.yaml
- plan-upgrade-agent.yaml
