---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hetzner-dns

resources:
# - configmap-state.yaml
- configmap-config.yaml
- ns.yaml
- serviceaccount.yaml
- cronjob.yaml
- rbac.yaml

configMapGenerator:
- name: hetzner-dns-scripts
  files:
  - update-dns.sh

images:
- name: alpine/curl
  newTag: 8.14.1
