apiVersion: apps/v1
kind: Deployment
metadata:
  name: aar-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aar-web
  template:
    metadata:
      labels:
        app: aar-web
    spec:
      containers:
      - name: aar-web
        image: lipanski/docker-static-website:2.6.0
        ports:
        - containerPort: 3000
          protocol: TCP
          name: http
        volumeMounts:
        - name: static-site 
          mountPath: /home/static
      volumes:
      - name: static-site
        configMap:
          name: aar-web
