---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: homeassistant-esphome
spec:
  parentRefs:
  - name: homeassistant
  hostnames:
  - esphome.home
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
      - name: homeassistant-esphome
        port: 6052
        weight: 1
