apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: homeassistant

resources:
- ../ext/middlewares/
- certificate.yaml
- configmap-homeassistant-env.yaml
- configmap-esphome-env.yaml
- gateway.yaml
- httproute-esphome.yaml
- httproute-homeassistant.yaml
- httproute-homeassistant-local.yaml
- ns.yaml
- statefulset-esphome.yaml
- statefulset-homeassistant.yaml
- statefulset-matter-server.yaml
- service-esphome.yaml
- service-homeassistant.yaml
- service-matter-server.yaml

images:
- name: ghcr.io/home-assistant/home-assistant
  newTag: "2026.1.1"
- name: ghcr.io/esphome/esphome
  newTag: "2025.12.6"
- name: ghcr.io/matter-js/python-matter-server
  newTag: "8.1.2"
