---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
- helmchart-cert-manager.yaml
- helmchart-dex.yaml 
- helmchart-oauth2-proxy.yaml 
- helmchartconfig-traefik.yaml
