apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-postgres
data:
  POSTGRES_DB: immich
  POSTGRES_USER: immich
  POSTGRES_INITDB_ARGS: "--data-checksums"
  PGDATA: /var/lib/postgresql/data/pgdata
