apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: adguard

resources:
- ns.yaml
- statefulset.yaml
- service-admin.yaml

images:
- name: ghcr.io/home-assistant/home-assistant
  newTag: "2025.11.2"
