apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: adguard

resources:
- gateway.yaml
- httproute-local.yaml
- ns.yaml
- statefulset.yaml
- service-admin.yaml
- service-dns.yaml
