apiVersion: v1
kind: Secret
metadata:
    name: dex-config
type: Opaque
stringData:
    config.yaml: ENC[AES256_GCM,data:3Jq90MjjYRlrCBTYflZ2lXYDzOYWEcF0Sm1F+Q+dbsQfcq47KUWSCzSTg3vv5Av/7zoTZ1ywfVO5jj7CgaVEoOzTEm9UWj+w5UTwq0+LfJ2B26MdM01J9hxDRYl/s9hloKHJ9n9hlOIXU7ZRkDlpsBx4FLeCujw6rSCA7pFXZBboj4uHF2U3XMyIvU9HLveC4DXQeRYsji+HnW6WgJKg30bIQ71vGZ5NYK8KfXZcTiCiDIwbTDqr5te+VQrdvMz3JT+kpjskt/0gYZr/xwnjs60JnCDK5UFSSqJwo6OIfAkJMZw47VI6AvD4X1viQ0ESaVGTHhYn5e9satXD1XIqk1sXOeMC/NPcdEV7kOYd3bK83iSBQvOmDsXz6VTzIuPxrY2TfE7uWUtvX0lr34Fr4Khu2FasD2OZwWoP8QelPv6Zxjhmg1lh5oQYtrCsb0M4+E/mQ+b16tVuPCs34hA4nnZkgUbRVbaxZtFb/EDiYKPqMfPAWWEsdGsdlmMDodFxRVXB/XeNa0xPBKcAb+t8Oz9UIdbVn4Nwgce/lFloPRsRJSchz2xT9hwts7ObZeX8DPKi1py0l8rjVPMSVcK13kfRdfyabzBvkO2I+B6JFJ3mTQc+d76PCYpDopwSquA9GQ60kefB1LV+lTQ2DaL3btJoKSUQElIv8DAUHyelrW3+hrBJNvg5IQ7GpLcmMIw6I0+D7Jzw5jPZgNpwcrkZZ2K0faNfI23Hu9IVzCsRkxzh17/PY3YrRrotduqxBsElOn727etBqWL1oxW6rsGzciE1hiIt+IkBr+t3mG4iEXavk7Njqb8Q9PqqvEmg0rpqNg==,iv:5Hla3ZfWb24wecT050r8IcaDzLaRkqOPxNTQCUc9Jw4=,tag:lJY4X61Ua+Sjmbi1z33qSA==,type:str]
sops:
    age:
        - recipient: age1f57t8jyuwattnn2ul724pwtrgl7q4jkwghqqyhk8t4vq5ed08pxqjcy98l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2a1BQMGVkSTg5TDByYjU5
            WjBEZG84YXlJalo1aXFDZFpESk5MK2k1dXpBCkd0R0c4Z2Jpa1JKRWtDZ1ZCMG9J
            b0l3TXlxSHN4bzQrR3ZqOWdwR3Y3TGMKLS0tIFJtMXFUUURpSEZmelBTWndFTTR5
            RTd6TTZoYlcxcU1kK1lwMEUzTWRkS2sKusDqs4ZjMFI6joP/Q1RI4DZOjJ54Bnx1
            6KGV5QN49kQj0xUea/n2GpTXA7b1MOgzwi2SDr8Q6kbMtJW+vl27hg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-25T12:23:19Z"
    mac: ENC[AES256_GCM,data:GIEaXtWd1RQizl8yhZXSrfO+NJ12YdDQQRsFNXL1gBKloL3pkEmxhbiF6e60jNC7Hm7Lbkck+xr8u7LAHn9uVIXurDGeof3YLgwUVioZfGmkT9rOc7W1VQAajbcpxT98Z+YeaL3vNpiEcKf+yVxhHyvJ/3X2Pu8wbHUI2QUQZ0Q=,iv:cGC+Ang4BvPw4wgUESor6gA8PN1COv/arXf4yLvtQ6E=,tag:WvYyQPXo0nZ/ouUOL23sHA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
