apiVersion: v1
kind: Secret
metadata:
    name: dex-config
type: Opaque
stringData:
    config.yaml: ENC[AES256_GCM,data:Sa7AXHvg474eKHTW6NwTuhroDjoXuVBlxqUmdGguAda72S57Gr3RZJbd/tfCFYN9beothfSkkCQsR2Vb2pf4yl7+Y/0CWN9xgQjF2L+Swnvkf77EQB3x9Im6ZMVQyXYItWVFgqUImljYevYopXmHNzGIMOKcKCzPEah741hdn3CgmGYBOTscdFqrd61pqloOPwUIuIQMDJJS50V07HWs+TkSVjl14YaRHLXrC1RwxxFMaXQMnOb5oeabOn2RDsQ2ym//YlWeCeWKiI47KaNep8SIOPaY6grhRlOodm1DwkRfGezCrgxIJ4ZdSPCn4IRhbzxFaZ57AhCiEIAbBwVD/p7KhrcqQfsKbANE5rQTkqiWageQ3S+LzT/8Tl3cTCYf5C0WRSjSCzvCiE7JWnLnL4FbyliElMsJY03ErY2VFK2LcA3+4w6ohzJQXQbo+XICnQMAYfypHfHHv38QGHC99FUhCwgQVQvuT1h8Uk34mPX9gQGzv54ZXpK2cIBFmhcKf24bgU1nU6zxFsVRU14KEtSq9+ujUi3KTV9kvJyMGn7jAGb1SX7/oJzowYEUhS0JSuBI6RGUbNuoEJRRbs3HLd3D4Ap5EFUwSOqFy9Db6bS4SvPCNARNry9ygO1F7DnsXLa2UqpbmG/+EqqxqsjPCQKVdJbMeqG1BdL4UBRcJ5eJody0kmTNH8e+BV+lZ6J8V6amSd0L6uxMoPreiFN1foZLmB5BaGNqkhW3qyhfKpjaJDzTdG4fBHNn/ZzirfqKMTa7N6WuDdRywQjDWNM1bS1KKh2WP+67X1Fn/OHA2Iw8+1ZAXIYZuZgqoh1neyr/7VAQDBuMgL+jV44c0v2CIO23zoV1wO9/Fod2H9B1qzgjYlBrbet9HEge53/b9JwT7BU42phYIRppbZcb7YROEGIVaiQygp5muVouO1Jxv2wwqRFpSZvvTBUuf3HfzjCq9rL+fkaCfh4qC/iN8/sxGCcCoHvtQZRvMzwGD6p/6n4C20Xijnouh8soALBOZNFrrkx+JVf8z/2X97LoBkdol4pQcxHiHdJY01afle6Mr8lEOdjC3CxqeHRHjybjCFJH8jw8kOt6791CGAIPLKksQ+vNFrsa8g57fAlNirJNPGM=,iv:CZgH5jI10aceYlLcs4xoySoOL9qHLRWr/J+HqF26cS8=,tag:tZjqYnqZEQbCyvEe8praKQ==,type:str]
sops:
    age:
        - recipient: age1f57t8jyuwattnn2ul724pwtrgl7q4jkwghqqyhk8t4vq5ed08pxqjcy98l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2a1BQMGVkSTg5TDByYjU5
            WjBEZG84YXlJalo1aXFDZFpESk5MK2k1dXpBCkd0R0c4Z2Jpa1JKRWtDZ1ZCMG9J
            b0l3TXlxSHN4bzQrR3ZqOWdwR3Y3TGMKLS0tIFJtMXFUUURpSEZmelBTWndFTTR5
            RTd6TTZoYlcxcU1kK1lwMEUzTWRkS2sKusDqs4ZjMFI6joP/Q1RI4DZOjJ54Bnx1
            6KGV5QN49kQj0xUea/n2GpTXA7b1MOgzwi2SDr8Q6kbMtJW+vl27hg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-02T11:44:30Z"
    mac: ENC[AES256_GCM,data:lX0oLuaLx7SuJ4H8IAc8dRyOmdNfUl63CzQc7/Vwk9eNhXEvuM5tByYYyNcntqHmFUU2Ysglmww85GGqvE/nusEXpXpGM1R7j/IZ4D2kPY1Eykm8b0sdt1utWxgEolMMgNcrliIwufQF5TbRfagQT3+dg6xhu3CiXvE329lEOas=,iv:p5PMB8zIH3ue4tXXeTXDpA43t1sg4m8qr04KjybqLkY=,tag:FdGbOGASj+AhjLC4+G8ZXw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
