apiVersion: v1
kind: Secret
metadata:
    name: dex-config
type: Opaque
stringData:
    config.yaml: ENC[AES256_GCM,data:ox8rVZS8dYYSwdV6MpiwrqxUi6MFaryRIUZTQs2F+z93pc3POUqvSGf2ma51PYU6sx5r5Y5b92WhSlq1gjRmUAOAmERVrhTJ2NrTjp12di8hA1HL0v/jDFKFeBqLzAuhYduVkZLntnwE16FfW1Ot5SBBheVaPxx0LTIj4oPFfSdILaP19C6lcgluC9gfSWahQszBmZaUaYi0DPjSQc2gnY2JLynfyUd1TkRsmBSbhW09A4YreLjGPvzH0jFGU1Na8/Kq0STLy5ViF4yqy5EaD9TXYe8djHItn+wzcA9pvIq1JNg9TeNFSM6vCM6EcQC9fbsw1SrRUaUAf9OLK0atzOjugRYJZ6PqPaUdiGa7ff8WMB3+8gdIBntvHzlR3ve5RrstCPye1SSNazvZFuP7O3PU4mqq6HDmHpGd4EBszgi5taD4u3GuYBbYluIlqH8IN8EIb5mWg3A94r2m/+P7UWcwGhRTQlGP/zIbXQ1ZUmU9RH0a86nQhm4h0PLb5nggolHN5DNdMNHfB/8mKTamcH3NALIFNCauVZ2/VD056KTKvrPzvLW9cM0rYZFQVyfaf7y0pAIo9lHDbIMeZtBBNPesyP8fQ9tEquyKAWpVn8NolM4SLEKOqr6usiqjKMJSgjlSbrU3kZuBIyfxzYaMhtwyihssYEkBXxTnY5WZml0RPggrHFRQNfutvlHeDPlU6hTz1MxE0BctPjv2T/zqv0nFTqNAwXs7766hTDq3KcDDqvUu4RKUabiN529Nl7Saxw==,iv:KqsaWXoi3c5/lFzM97EQ9bGksQFdKuBfjFOrRq+atYk=,tag:HxDnPV5AbyJx9Fm//Fck1Q==,type:str]
sops:
    age:
        - recipient: age1f57t8jyuwattnn2ul724pwtrgl7q4jkwghqqyhk8t4vq5ed08pxqjcy98l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2a1BQMGVkSTg5TDByYjU5
            WjBEZG84YXlJalo1aXFDZFpESk5MK2k1dXpBCkd0R0c4Z2Jpa1JKRWtDZ1ZCMG9J
            b0l3TXlxSHN4bzQrR3ZqOWdwR3Y3TGMKLS0tIFJtMXFUUURpSEZmelBTWndFTTR5
            RTd6TTZoYlcxcU1kK1lwMEUzTWRkS2sKusDqs4ZjMFI6joP/Q1RI4DZOjJ54Bnx1
            6KGV5QN49kQj0xUea/n2GpTXA7b1MOgzwi2SDr8Q6kbMtJW+vl27hg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-25T09:35:48Z"
    mac: ENC[AES256_GCM,data:pZS2BuY8Fn3+jM1ZdZ38E/2j01pN3OluudmE1R7TCi1BLpWoq5iqcHBJPMbR8MjjP4KOMishC2cGU86thdaeAdw56MFSqtJsqIEb8YlWCaSZqNG2hQ7oG3mxtMlNmDkUojZsLESGqQzPQC4Ex7tJ5/2T23zqbT+pLvhLFw9SDno=,iv:tFHM22t6r92Yi/ooeMB+ydtx5YeVaQnzhqSsApj6buc=,tag:J/fd0oqfDx6CFsKpJzU7pA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
