apiVersion: v1
kind: Secret
metadata:
    name: dex-config
type: Opaque
stringData:
    config.yaml: ENC[AES256_GCM,data:72n2MsyMd7PcmYxu+2cVw4K8WSiKLUOx04LvnNYgxmKfuTNAgLh1pNd6tSWkux3lopJZf/6FoSIN4P7PI4+FaMeCFrubQItYdgUAFQNodPQgROc3MalzSUzJfnM4DMOYup+x31GanzGnZr4/2gmjEsCgyz7WvY0b7kJT9/mfTe2/RejIYXYzGb8wTU6YaExwT2gbyPonReGL5jampDrm4t8Dpyhq72nqngg1xTmzMn4shhzZe2ZVAGg81rEh/RxAjUZ4qeHtqYoFY/4yrg6a1dy9TNJAnrsS93z9YP6SWfidEmuETQH/JuaORwO7M1uPoEnxkaPb1rvEwNnDck6sLNv9Us0eUZaDHqlSlnB8kz6VpLzYN+jL9Fx37ejS+OjNVfkodCJQEgQ5LFDqMfDhdiViLx3MukheCOW4fM3owrn4pmQsLFJ4A9tSTWHnOmUf+JQmOpCDkbFjX7exjmxodQ5Sm79tlNiTIsGu/PqzeDlWTnw4vmQKbnuTKGKYxLNQfSVQ2xZzK7WWFavX8PF1x43uU4QhOka+f7kuj789zVYsb0x7v7ZUoC3YYAKtfQak1WUbfoiMPAwHvbUH98yft0ZasXzJbcxsuwaogZdI5smyQNoYMWrtWNvtR9n6w3OJaw55tkf9XHWT2SEmy6KAhw66PI8gOs7zqNzqo8ZOdhAqcEKy4LK0gIqQFpzQ+BHOvpYCD0CHs3wfNyWkQDHdxLCazOpUR8ovETdFmaMiKGvT/InDur3UbUac/anvTRkUgQlbNCodD1r/vZxc6m6oV2yqOz1t0i0LsCVxwXR8nomZrYtd3ntPm8oUYEMVM5Mww42TWFY5uGpaGYYp7lK8iY9WzBxi47x+8LtIu3EHqHSWBvtt5LEtaOEfoVh3o00lng==,iv:dVZlLgIqltdKzbNjZdM1k/ziZSOBKnspdNFkcH4PVpE=,tag:LiiqIN6d8tQfPohAWo2zHg==,type:str]
sops:
    age:
        - recipient: age1f57t8jyuwattnn2ul724pwtrgl7q4jkwghqqyhk8t4vq5ed08pxqjcy98l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2a1BQMGVkSTg5TDByYjU5
            WjBEZG84YXlJalo1aXFDZFpESk5MK2k1dXpBCkd0R0c4Z2Jpa1JKRWtDZ1ZCMG9J
            b0l3TXlxSHN4bzQrR3ZqOWdwR3Y3TGMKLS0tIFJtMXFUUURpSEZmelBTWndFTTR5
            RTd6TTZoYlcxcU1kK1lwMEUzTWRkS2sKusDqs4ZjMFI6joP/Q1RI4DZOjJ54Bnx1
            6KGV5QN49kQj0xUea/n2GpTXA7b1MOgzwi2SDr8Q6kbMtJW+vl27hg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-30T21:01:55Z"
    mac: ENC[AES256_GCM,data:MmBEklCt2y+SaBejP50fn3nn6yz8h2iQ73NnH2u04ntJYFZAh2zbtgEfFYCEiuASbmxTx7ZuKqvspZKeTaiDtPsbCPcdqhIDS8eJcAZS40WOIUuexPgz/cmxjVbgr+AVgJKw3DrMGWspNp5+g7xv/jpwu5SbKKXIffmbwMpxavU=,iv:PT6MyKbX2Vsf5GCn7NThGgbUB3AE7NSnfp5SIGsHeV4=,tag:oVkfojDrSfwuhEczahQRtg==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.11.0
